### ISSUE TITLE
Verify partner links in footer

### ISSUE THREAD

**Issue by peterdesmet** [enram/globam.science#12]

**Comment by baptischmi** [comment]
Vogelwarte uses a Swiss domain, ending with ".ch": 
https://www.vogelwarte.ch/en/home/

**Comment by peterdesmet** [comment]
Thanks, corrected in 92e6102. Any other issues?

**Comment by peterdesmet** [comment]
@tommason are all the other organizations and their order fine? Can this issue be closed?

**Comment by tommason** [comment]
@peterdesmet Organisations and links look good to me. I'm not sure how they're ordered, but could be Swiss Ornithological Institute first and then the rest ordered alphabetically?

**Comment by peterdesmet** [comment]
They are currently ordered as the partners on the proposal, but what you suggest makes more sense.

**Comment by peterdesmet** [comment]
Updated and closed.
