### ISSUE TITLE
Add team members

### ISSUE THREAD

**Issue by peterdesmet** [enram/globam.science#3]
In this file: https://github.com/enram/globam.science/blob/master/_data/team.yaml

Info that can be included for each person:

- Name
- Role
- Photo
- Bio (short, but can contain links)
- ORCID: https://orcid.org
- Email (if you want this public)
- GitHub username (if you want this public)
- Twitter username (if you want this public)

**Comment by tommason** [comment]
Profiles added for four team members. How do you add email addresses, do you need 'mail to:' or similar?

**Comment by peterdesmet** [comment]
👍 no, just the email address (as you did for Andrew) is fine. The "mailto:" is added by the layout of the page.

**Comment by peterdesmet** [comment]
Here's the list of team members as submitted to the Belmont forum. Not sure if it is complete, but it could serve as a checklist (checked people are already on [team page](https://globam.science/team/)):

### Swiss Ornithological Institute

- [x] Silke Bauer: Consortium Lead
- [x] Birgen Haest: Team Member
- [x] Felix Liechti: Team Member
- [x] Thomas Mason: Team Member
- [x] Cecilia Nilsson: Fully Self-Financed Collaborator
- [x] Raphael Nussbaumer: Postdoc
- [x] Baptiste Schmid: **not included in BELMONT forum list**

### University of Exeter

- [x] Jason Chapman: In-Kind Collaborator

### Research Institute for Nature and Forest

- [x] Peter Desmet: Partner PI
- [x] Nicolas Noé: Team Member

### Cornell Lab of Ornithology

- [x] Andrew Farnsworth: Partner PI
- [x] Adriaan Dokter: Team Member

### Finnish Meteorological Institute

- [x] Jarmo Koistinen: Partner PI
- [ ] Terhi Mäkinen: In-Kind Collaborator
- [x] Nadja Weisshaupt: Team Member

### University of Amsterdam

- [x] Judy Shamoun-Baranes: Partner PI
- [x] Bart Kranstauber: Team Member
- [ ] Hidde Leijnse: Stakeholder Representative

**Comment by peterdesmet** [comment]
@bart1 and @niconoe, as a GloBAM team members, we would like to add you to https://globam.science/team/

Since you're familiar with GitHub, can you write a short bio + photo (can be externally hosted, e.g. twitter profile picture) and add yourself to https://github.com/enram/globam.science/blob/master/_data/team.yml, alphabetically on family name. So @bart, below Birgen Haest and @niconoe, below Cecilia Nilsson.
