### ISSUE TITLE
Provide better titles for the introductory talks

### ISSUE THREAD

**Issue by peterdesmet** [enram/globam.science#37]
` Provide better titles for the introductory talks?`
I'd suggest to put them on TBD for now (to not further delay publication), and one of us sends an email to the keynote speakers to request their tentative titles.

_Originally posted by @BirgenH in https://github.com/enram/globam.science/pull/36#discussion_r862096931_

**Comment by peterdesmet** [comment]
I have left the titles as is (better than TBD), but it would still be good to ask the speakers. I also don't know if Jeff Buler's talk is considered a keynote (he is not listed as a keynote speaker)? @BirgenH can you provide that information?

- [ ] Felix Liechti keynote title
- [ ] Dan Sheldon keynote title
- [ ] Jeff Buler session introduction title and whether I should mark it as keynote
- [ ] Bayo Gao keynote title
- [ ] Silke Bauer & Judy Shamoun-Baranes keynote title

Thanks!

**Comment by BirgenH** [comment]
@peterdesmet: Jeff Buler's talk is a keynote talk, yes! (It was changed it during program planning).

**Comment by peterdesmet** [comment]
Ok, I have indicated it as such. He's now the only keynote speaker without a bio at the top: https://globam.science/irac-2022/#keynote-speakers Is it possible to provide one?

**Comment by peterdesmet** [comment]
All keynotes now have a title. And Jeff has a bio.
