### ISSUE TITLE
Decide what image to include on home page

### ISSUE THREAD

**Issue by peterdesmet** [enram/globam.science#8]
Currently this image: https://github.com/enram/globam.science/blob/master/assets/img/kelvin-yan-1333097-unsplash.jpg. @silkebauer @tommason is that ok?

If so, I will reduce it in size.

**Comment by peterdesmet** [comment]
Size reduction already done: https://github.com/enram/globam.science/commit/c910a44daabefdc10685be39f1983e58f9b8856a

**Comment by CeciliaNilsson709** [comment]
Tried making a higher resolution version of the biorad bloom, and don't think it gets much better than this... but also I don't really know what I am doing, so let me know if it should be in another format/size/resolution. (I am saving it with ggsave, currently pdf with `width=40, height=20, dpi=1200`)
[bloom.pdf](https://github.com/enram/globam.science/files/3356474/bloom.pdf)

**Comment by tommason** [comment]
Biorad bloom looks cool, would it also be possible to have it as a visualisation? It could work as an image lower on home page, or on about page (I was intending to put more figs on there too). I've had a go at making an composite image for the banner which conveyed both radar and ecology- what do you think of something like these:
![home_page_candidate_1](https://user-images.githubusercontent.com/25060742/60653116-b4861c80-9e49-11e9-856a-8cacb1186fcf.png)
![home_page_candidate_2](https://user-images.githubusercontent.com/25060742/60653117-b4861c80-9e49-11e9-9c28-c6e913aeb2ba.png)

**Comment by tommason** [comment]
Or alternatively these, with the latter one having GloBAM text added over it. Also, we thought the text "Towards monitoring etc" could maybe be moved to the header. 
![home_page_candidate_3](https://user-images.githubusercontent.com/25060742/60659125-ecdf2800-9e54-11e9-9fc7-446f9fea9101.png)
![home_page_candidate_4](https://user-images.githubusercontent.com/25060742/60659127-ecdf2800-9e54-11e9-8cd2-c91a26c8fa16.png)

**Comment by peterdesmet** [comment]
Here are the screenshots of the suggested photos:

![bloom](https://user-images.githubusercontent.com/600993/60663802-852eda00-9e60-11e9-9377-030c111c7dc7.png)
![far](https://user-images.githubusercontent.com/600993/60663821-8eb84200-9e60-11e9-8869-2f9ac4b5949e.png)
![close](https://user-images.githubusercontent.com/600993/60663812-895af780-9e60-11e9-98e1-3aa4a150f579.png)
![text](https://user-images.githubusercontent.com/600993/60663818-8c55e800-9e60-11e9-93bb-132e0b12ff0d.png)
![logo](https://user-images.githubusercontent.com/600993/60663808-86f89d80-9e60-11e9-92a8-92098418895c.png)

**Comment by peterdesmet** [comment]
In my opinion, we should:
- Stick to a single photo rather than a composite for the header photo. Since every page can have a different image, we can cover multiple images that way.
- Not include the logo: it's already included in the navbar + the white background doesn't work that well with the white text + note that the header image will have a different size depending on your screen width (e.g. mobile vs desktop), so even if it fits all nicely in one format, it might not in a different format.

**Comment by silkebauer** [comment]
Some thoughts:
- I like the colorful radar burst image for the startpage. If we keep the Title across the image, we could actually cull the logo and "GloBAM" in the upper-left corner and have "Home" there.
- A composite image is also nice, including the one with the logo & title in the middle. Text should then be confined to middle part (perhaps cull "Towards") and logo & GloBAM from upper left corner replaced with home (otherwise too redundant)

What do you all think of: we take the colorful radar-burst image with title for the start page, and composite ones for the other pages? And replace the logo & "GloBAM" with home?

**Comment by peterdesmet** [comment]
1. 👏 for the radar burst (with some minor tweaking to make it look more like the bioRad logo)
2. The logo + `GloBAM` should stay in the white navbar (even if it looks a bit repetitive on the homepage), as it is used on every page to indicate to users that they are on the GloBAM website (e.g. https://globam.science/about/).
3. The `Home` link in the navbar _is_ repetitive, but helpful for some users (I have no opinion if it should stay or go).
4. The white text on top of the background image is variable: the text and thus its length depends on the page you are on (e.g. https://globam.science/news/welcome-to-jekyll/) and the width of your screen. It's thus not possible to cull or confine the text. ☺️ That is also why composite images are harder to use as background images, as the edges will sometimes change in relation to the text. A single image is easiest.

**Comment by peterdesmet** [comment]
So my suggestion would be to use the images that @tommason has included in the composite above, but spread them as single images over multiple pages (about, team, content).

**Comment by silkebauer** [comment]
Ok with me to use the photos by @tommason - they just look a bit more lively than the grey-ish radar one. Just shorten the title-text by culling "Towards" and maybe also "GloBAM", i.e. only leave "Monitoring, understanding ..."

**Comment by peterdesmet** [comment]
"Towards" is now dropped: https://globam.science/

**Comment by CeciliaNilsson709** [comment]
++ for having the bloom on the title page (if you make the white radar dot in the middle black instead 😬). I could maybe make it in to a animation, but would need to find the surrounding scans etc. That would be nice if we put it further down on the page.

++ for the other images spread out (although I really like the solid color banners too).

++++++ for keeping both logo and "home" on all pages, it's not repetitive, it's good structure 👌

**Comment by peterdesmet** [comment]
@CeciliaNilsson709 Yeah, the white dot bothered me too. I think we can avoid colouring it black if I use more of a purple overlay like I did for the bioRad logo and move it up a little. 🤷‍♂️

An animated gif in the header could technically work. 🤔Would try with a fixed one first. If you want to see how an animated ppi plot further down the page looks like, see http://www.enram.eu/ ☺️

Question: what name is more intuitive for the element we are discussing: `header` or `banner`?

**Comment by tommason** [comment]
Bloom on home page banner (banner is more intuitive to me) and photos on other pages sounds good to me!

**Comment by peterdesmet** [comment]
This OK?

![bloom_screenshot](https://user-images.githubusercontent.com/600993/60713381-4741bc80-9f19-11e9-8d9d-4cbf0475a5fc.png)

**Comment by tommason** [comment]
Looks good. White writing in title is nice and clear.

**Comment by CeciliaNilsson709** [comment]
The head-banner looks good! But maaaaybe a little bit too much like the biorad logo now? Don't know if that could be confusing, but maybe no one would notice anyway.

**Comment by peterdesmet** [comment]
Now updated: https://globam.science/ @CeciliaNilsson709 I someone finds it confusing, we can always change it again. 😌

**Comment by CeciliaNilsson709** [comment]
❤️ it!

**Comment by jshamoun** [comment]
Website looks great!
